init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh r_binary_install proto rgdal

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

environment:
  global:
    R_CHECK_ARGS: "--no-build-vignettes --no-manual --as-cran"
    _R_CHECK_FORCE_SUGGESTS_: FALSE
  matrix:
    - R_VERSION: release
      R_ARCH: x64
      USE_RTOOLS: true

notifications:
  - provider: Slack
    auth_token:
      secure: S3AcHEoJHUtahR5N8ConStS8oV/+x34tS1bDGM3OD0QxDKBBxufeiMmXQsId1gZu
    channel: '#builds'

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
